config/routes.rb
AuthenticationEngine::Engine.routes.draw do	
  root to: "welcome#index"
  resources :users, except: [:delete] do
  	collection do
  		get :sign_in
  		delete :sign_out
  		post :sign_in
  	end
  end
end

app/models/authentication_engine/application_record.rb
module AuthenticationEngine
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/authentication_engine/user.rb
module AuthenticationEngine
  class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

    validates :fullname, :username, presence: true

    def email_or_fullname_or_username
    	fullname || username || email
    end
  end
end

app/controllers/authentication_engine/application_controller.rb
module AuthenticationEngine
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :current_user
    private

    def current_user
    	if session[:user_id].present?    		
    		@current_user = User.find_by(id: session[:user_id])
    	else
    		@current_user = nil
    	end
    end

  end
end

app/controllers/authentication_engine/users_controller.rb
require_dependency "authentication_engine/application_controller"

module AuthenticationEngine
  class UsersController < ApplicationController

    before_action :find_user, only: [:edit, :update, :destroy, :show]

  	def index
  		@user = User.all
  	end

  	def new
  		@user = User.new
  	end

    def show
      unless @user.present?
        redirect_to root_path, notice: 'Invalid User'
      end      
    end

  	def create
      @user = User.new(user_params)
      if @user.save
      	session[:user_id] = @user.id
        redirect_to root_path, notice: 'User was successfully created.'
      else
        render :new
      end  		
  	end

    def edit
      unless @user.present?
        redirect_to root_path, notice: 'Invalid User'
      end
    end


    def update
      if @user.update(user_params)
        redirect_to root_path, notice: 'User was successfully created.'
      else
        render action: :edit
      end
    end


  	def sign_in
  		if request.post?
	  		@user = User.find_by(email: params[:email])
	  		if @user.present? && @user.valid_password?(params[:password])
	  			session[:user_id] = @user.id
	  			redirect_to root_path, notice: 'Successfully log in'
	  		else
	  			redirect_to '/users/sign_in', notice: 'Invalid User'
	  		end
	  	end
  	end

  	def sign_out
  		session[:user_id] = nil
  		redirect_to root_path, notice: 'Successfully logout'
  	end

  	private

    def find_user
      @user = User.find_by(id: params[:id])
    end

  	def user_params
  		params.require(:user).permit(:fullname, :username, :email, :password, :password_confirmation)
  	end

  end
end

app/controllers/authentication_engine/welcome_controller.rb
require_dependency "authentication_engine/application_controller"

module AuthenticationEngine
  class WelcomeController < ApplicationController
    def index
    end
  end
end

app/helpers/authentication_engine/application_helper.rb
module AuthenticationEngine
  module ApplicationHelper
  end
end

app/helpers/authentication_engine/users_helper.rb
module AuthenticationEngine
  module UsersHelper
  end
end

app/helpers/authentication_engine/welcome_helper.rb
module AuthenticationEngine
  module WelcomeHelper
  end
end

app/views/authentication_engine/users/edit.html.erb
<div class="col-md-6">
  <h1>Edit User</h1>
  <hr>
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h4><%= pluralize(@user.errors.count, "error") %> prohibited this blog from being saved:</h4>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :email %>
      <%= f.object.email %>
    </div>
    <br/>
    <div class="field">
      <%= f.label :fullname %>
      <%= f.text_field :fullname, class: 'form-control' %>
    </div>
    <br/>
    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>
    </div>

    <hr>
    <div class="actions">
      <%= f.submit "Update", class: 'btn btn-primary' %>
      <%= link_to "Cancel", '/blogs', class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

app/views/authentication_engine/users/new.html.erb
<div class="col-md-6">
  <h1>Sign up</h1>
  <hr>

  <%= form_for(@user) do |f| %>

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h4><%= pluralize(@user.errors.count, "error") %> prohibited this blog from being saved:</h4>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :fullname %>
      <%= f.text_field :fullname, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
    </div>

    <hr>
    <div class="actions">
      <%= f.submit "Submit", class: 'btn btn-primary' %>
      <%= link_to "Sign In", '/users/sign_in', class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

app/views/authentication_engine/users/show.html.erb
<h1>
  View User Profile
  <small class="pull-right">
		<% if @user == @current_user %>
			<%= link_to 'Edit', "/users/#{@current_user.id}/edit", class: 'btn btn-sm btn-primary' %>
		<% end %>
		<%= link_to 'Back', :back, class: 'btn btn-sm btn-primary' %>
  </small>
</h1>
<hr>


<% if @user.present? %>
	<p class="col-md-12"> FullName : <b><%= @user.fullname %> </b></p>
	<p class="col-md-12"> Email  : <b><%= @user.email %> </b></p>
	<p class="col-md-12"> Username : <b><%= @user.username %> </b></p>
	<div class="clearfix"></div>
<% end %>

app/views/authentication_engine/users/sign_in.html.erb
<div class="col-md-6">
  <h2>Sign In</h2>
  <hr>
  <%= form_tag '/users/sign_in', method: 'post' do %>
    <div class="form-group">
      <label for="email">Email:</label>
      <%= email_field_tag :email, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <%= password_field_tag :password, '', class: 'form-control' %>
    </div>
    <hr>
    <div class="actions">
      <%= submit_tag "Sign In", class: 'btn btn-primary' %>
      <%= link_to "Sign Up", '/users/new', class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

app/views/authentication_engine/welcome/index.html.erb
<h2>Welcome to Engine Demo</h2>
<hr>
<% if @current_user.present? %>
	<p class="col-md-4"> FullName : <b><%= @current_user.fullname %> </b></p>
	<p class="col-md-4"> Email  : <b><%= @current_user.email %> </b></p>
	<p class="col-md-4">Username : <b><%= @current_user.username %> </b></p>	
<% end %>

app/views/layouts/authentication_engine/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>Authentication engine</title>
  		<%= stylesheet_link_tag    "authentication_engine/application", media: "all" %>
  		<%= javascript_include_tag "authentication_engine/application" %>
  		<%= csrf_meta_tags %>
	</head>
	<body cz-shortcut-listen="true">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Engine Demo</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class=""><a href="/">Home</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>	
    <div class="container">
 			<% flash.each do |name, msg| %>
    		<%= content_tag :div, msg, class: "alert alert-info" %>
  		<% end %>
      <br/>
      <div class="pull-left">
        <% if @current_user.present? %>
          <%= link_to 'Logout', sign_out_users_path, method: :delete, data: {confirm: 'Are you sure want to logout?'}, class: 'btn btn-danger' %>
          <%= link_to 'Blogs', '/blogs', class: 'btn btn-primary' %>
        <% else %>
          <%= link_to 'Sign In', sign_in_users_path, data: {disable_with: 'Loading...'}, class: 'btn btn-primary' %>
          <%= link_to 'Sign Up', new_user_path, data: {disable_with: 'Loading...'}, class: 'btn btn-primary' %>
        <% end %>      
      </div>
      <div class="clearfix"></div>
      <hr>
			<%= yield %>
		</div>
	</body>
</html>